export enum BroadcastServiceEmitType {
  settings = 'SETTINGS',
  showcase = 'SHOWCASE',
  brand = 'BRAND',
  'landing-page' = 'LANDINGPAGE',
  apps = 'APPS',
  blog = 'BLOG',
  cart = 'CART',
  category = 'CATEGORY,',
  freight = 'FREIGHT',
  menu = 'MENU',
  newsletter = 'NEWSLETTER',
  pages = 'PAGES',
  product = 'PRODUCT',
  scripts = 'SCRIPTS',
  sections = 'SECTIONS',
  shop = 'SHOP',
  sidebar = 'SIDEBAR',
  user = 'USER'
}
