export enum BroadcastServiceEmitType {
  settings = 'Settings',
  showcase = 'Showcase',
  brand = 'Brand',
  'landing-page' = 'LandingPage',
  apps = 'Apps',
  blog = 'Blog',
  cart = 'Cart',
  category = 'Category,',
  freight = 'Freight',
  menu = 'Menu',
  newsletter = 'Newsletter',
  pages = 'Pages',
  product = 'Product',
  scripts = 'Scripts',
  sections = 'Sections',
  shop = 'Shop',
  sidebar = 'Sidebar',
  user = 'User'
}
