import { nullable } from './NullableTypes'

export interface Shop {
  id: number
  slug: string
  partner_id?: nullable<number>
  customer_service_sell_id?: nullable<number>
  superlogica_id?: nullable<number>
  name?: nullable<string>
  phrase?: nullable<string>
  description?: nullable<string>
  keywords?: nullable<string>
  email?: nullable<string>
  email_from?: nullable<string>
  industry?: nullable<string>
  knowledge?: nullable<string>
  sales_urgency?: nullable<string>
  rating?: nullable<string>
  domain?: nullable<string>
  azion_domain_id?: nullable<number>
  azion_certificate_id?: nullable<number>
  ssl?: nullable<boolean>
  redirect_temporary?: nullable<boolean>
  shipping_time_additional?: nullable<string>
  shipping_time_additional_kit?: nullable<string>
  shipping_restriction_message?: nullable<string>
  schedule_delivery?: nullable<string>
  append_to_head?: nullable<string>
  append_to_body?: nullable<string>
  theme_id?: nullable<number>
  policy_footer?: nullable<string>
  notifications?: nullable<string>
  company?: nullable<string>
  cgc?: nullable<string>
  zipcode?: nullable<string>
  city?: nullable<string>
  state?: nullable<string>
  street?: nullable<string>
  number?: nullable<string>
  detail?: nullable<string>
  district?: nullable<string>
  phone?: nullable<string>
  checkout_note_active?: nullable<boolean>
  checkout_note_label?: nullable<string>
  catalog?: nullable<boolean>
  customer_register_for?: nullable<string>
  customer_register_approves?: nullable<string>
  customer_register_company?: nullable<boolean>
  customer_register_individual?: nullable<boolean>
  facebook_connect?: nullable<boolean>
  google_connect?: nullable<boolean>
  tracker_google_analytics?: nullable<string>
  tracker_google_conversion?: nullable<string>
  tracker_facebook_pixel?: nullable<string>
  ideris_connect?: nullable<string>
  terms_user_id?: nullable<number>
  terms_accepted_at?: nullable<number>
  users_count?: nullable<number>
  products_count?: nullable<number>
  phone_service_code?: nullable<number>
  organization?: nullable<string>
  suspended_at?: nullable<string>
  registration_completed_at?: nullable<string>
  active?: nullable<boolean>
  created_at?: nullable<string>
  updated_at?: nullable<string>
  deleted_at?: nullable<string>
}
